### ISSUE TITLE
Use parallel zip and unzip

### ISSUE THREAD

**Issue by korenmiklos** [e3krisztian/bead#35]
`bead save` is painfully slow with a few GB of data. Can we use parallel processing to speed up zipping?

**Comment by e3krisztian** [comment]
`bead save` reads up the file twice, once for calculating the crypto-hash, then storing into the zip file.  For multi-gigabyte files, both operations can take 10+ seconds (depending on CPU and/or server load).  There is the possibility to run these operations in parallel, but `save` will still remain slow (I would expect less than 2x speedup - I think hash calculation is faster than compression).

So unfortunately zipping can not scale by spreading over multiple processes (zip writing must be sequential), however unzipping can most probably be sped up by using multiple processes.

**Comment by e3krisztian** [comment]
A new release is on the way, with some features enabling potentially huge speed ups, but they will not help with `save` being painfully slow.

It is compression, that makes `save` slow, compressing several GBs of data is still slow/noticeable today.

Multi-GB beads are definitely stretching the limits of the current design/implementation.
They work, but saving them should not be an every minute workflow (otherwise the archives would quickly fill up all storage), and usually it should be worth waiting for compression.

These are the options I can think of:
- do not compress anything (archives would most probably be bigger)
- add a mechanism (e.g. environment variable) to conditionally not compress on save
- implement a very efficient big-ish data storage backend (beads need not be archived to zip files, they could be stored like uncompressed directories, s3 folders, etc., however it would require quite a bit of work to add another "box" and "bead-archive" format at the moment)

Depending on data content (e.g. already compressed files) not compressing anything can be a viable option.
Maybe for some users it might be worth adding an environment variable to not compress? (`export BEAD_ZIP_COMPRESSION=off` - this is just an idea, it is not yet implemented)

----

@korenmiklos the compression-off through environment variable is relatively easy to implement, but you need to convince me with data, that you really need it.

Could you check the speed difference with the `zip` command on a slow workspace?
- `time zip -r archive.zip multi-gb-directory` - compresses data
- `time zip -0 -r archive.zip multi-gb-directory` - no compression, store data as is

It would be best if you could do it on a calm system (no other load), and also
- delete the resulting `archive.zip` between `zip` commands (to prevent an update, which is slower)
- repeat the above commands twice and compare only the second timings to mitigate the difference caused by the OS disk-cache.

I am also curious about the data stored, for which `save` is painfully slow:
- is it a few big files?
- is it many smaller files?
- size/file count=?

**Comment by e3krisztian** [comment]
If you do this measurement on your data, please give 
- the time it took to zip
- and the zipped size

for both the compressed and store-only zip file, 
- and also the size/file-count ratio of the original data.

**Comment by e3krisztian** [comment]
@korenmiklos it was really easy, so turning off compression via environment variable is implemented in 5c2ae9f3b96905291d6d234d677645a6ee26acea

----
I have experimented with other compression options, but decided against enabling them - I could not decompress the one compressed with LZMA with info-zip's unzip, as it lacked support (BZip2 worked, but still decided against it).
